### ISSUE TITLE
Error in compile function

### ISSUE THREAD

**Issue by HieuTrLuu** [giesekow/deepvesselnet#3]
Environment:
-tensorflow:1.14.0
-tensorflow-gpu:1.4.0
-numpy: 1.14.0
-keras:2.0.8
-sklearn:0.20.4

-------------------------------------------------------------------------------------------------

Code used is the Usage section in the read me:

from dvn import FCN, VNET, UNET  # import libraries
net = FCN()                                 # create the network object (You can replace FCN with VNET or UNET),
					    # there is a 'dim' parameter which takes the values 2, or 3 to build 2D or 3D versions of the networks (Default is 3)
					    # there is a 'cross_hair' parameter which builds a network with cross-hair filters when set to True (Default is False)

net.compile()                               # compile the network (supports keras compile parameters)

--------------------------------------------------------------------------------------------
Error:

Traceback (most recent call last):
  File "testDVN.py", line 7, in <module>
    net.compile()                               # compile the network (supports keras compile parameters)
  File "/home/luu/deepvesselnet/dvn/fcn.py", line 89, in compile
    super(FCN, self).compile(models={'default': {'loss': loss, 'optimizer': optimizer, 'metrics': metrics}})
  File "/home/luu/deepvesselnet/dvn/net.py", line 108, in compile
    self._compile(models, **kwargs)
  File "/home/luu/deepvesselnet/dvn/net.py", line 112, in _compile
    self.build()
  File "/home/luu/deepvesselnet/dvn/net.py", line 58, in build
    cur_input = lay(**params)(inputs)
  File "/home/luu/anaconda3/envs/py2-3/lib/python2.7/site-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "/home/luu/anaconda3/envs/py2-3/lib/python2.7/site-packages/keras/layers/convolutional.py", line 125, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.

Can you help me with this

Best regards

**Comment by giesekow** [comment]
I think the code uses `image_data_format` of `channels_first` hence if you use the default `keras.json` settings you get this error. because the default value is `channels_last`. you have to change this value. I will change this behaviour later but you can change the settings now to meet that requirement

**Comment by giesekow** [comment]
Let me know if this works for you

**Comment by HieuTrLuu** [comment]
The updated version works. Thank you
